(require 'draw)
(draw-scale 144 12)
(define band
  (lambda (colour position)
    (apply draw-rgb colour)
    (draw-move 0 position)
    (draw-line 1 position)
    (draw-line 1 (+ 1 position))
    (draw-line 0 (+ 1 position))
    (draw-fill)
    (+ position 1)))
(draw-start "rainbow.ps")
(reduce band 0 '((1 0 .3) (1 .525 .2) (1 1 .3) (0 .75 0) (.2 .2 .9) (.76 0 .85)))
(draw-end)
(exit)
